"""Add user_side to debate

Revision ID: 05ab2290d7b2
Revises: 3c8b8806c097
Create Date: 2026-03-01 07:07:23.622253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ab2290d7b2'
down_revision: Union[str, Sequence[str], None] = '3c8b8806c097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debates', sa.Column('user_side', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debates', 'user_side')
    # ### end Alembic commands ###
