"""Add claims to debate

Revision ID: 3c8b8806c097
Revises: 013d5ca2dad4
Create Date: 2026-02-28 22:47:49.480518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c8b8806c097'
down_revision: Union[str, Sequence[str], None] = '013d5ca2dad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debates', sa.Column('pro_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('debates', sa.Column('con_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debates', 'con_claims')
    op.drop_column('debates', 'pro_claims')
    # ### end Alembic commands ###
